// all ActionTypes as ENUM
export enum ActionTypes {
    SET_MAP = 'SET_MAP',
    SET_ACTIVE_BUTTON = 'SET_ACTIVE_BUTTON',
    SHOW_OVERLAY = 'SHOW_OVERLAY',
    SET_SELECTED_FEATURE = 'SET_SELECTED_FEATURE'
}
