version: '2'
services:
  shogun-nginx:
     build:       
       context: nginx/     
     ports:       
       - 80:80
     depends_on:
       - shogun-geoserver
  shogun-geoserver:
    image: terrestris/geoserver:latest
    #build: 
    #  context: gs-image/
    ports:
      - 1235:8080
    volumes:
      - ./geoserver_data:/opt/geoserver_data:Z
      - ./geoserver/additional_libs:/opt/additional_libs:Z
    depends_on:
      - shogun-postgis
  shogun-postgis:
    image: mdillon/postgis:9.6-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: shogun
      POSTGRES_PASSWORD: shogun
    volumes:
      - ./postgresql_init_data:/docker-entrypoint-initdb.d
      - ./postgresql_data:/var/lib/postgresql/data:Z
